### ISSUE TITLE
I can't figure out how to use the Python plugin

### ISSUE THREAD

**Issue by TrNullFree** [elfmz/far2l#1451]
Latest far2l - version 2.4.1-b3994280-beta Linux x86_64 (Ubuntu 22.10)
I can't figure out how to use the Python plugin.

I tried the py:load command:
py:load ucharmap 
_py:load: command not found_

Is the plugin broken?

Found /tmp/far2-py log file.
It looks strange, especially  '/usr/lib/python311.zip' :

2022-12-14 21:03:13,591 pluginmanager:25:DEBUG: ******************** start
2022-12-14 21:03:13,591 pluginmanager:26:DEBUG: sys.path=['/usr/lib/python311.zip', '/home/user/.config/far2l/plugins/python', '/usr/local/share/far2l/Plugins/python/plug', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/dist-packages', '/usr/lib/python3/dist-packages']
2022-12-14 21:03:13,591 pluginmanager:27:DEBUG: cwd=/usr/local/lib/far2l/Plugins/python/plug
2022-12-14 21:03:13,592 pluginmanager:34:ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/local/share/far2l/Plugins/python/plug/far2l/__init__.py", line 1, in <module>
    from .pluginmanager import PluginManager
  File "/usr/local/share/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 44, in <module>
    from .far2lcffi import ffi
  File "/usr/local/share/far2l/Plugins/python/plug/far2l/far2lcffi.py", line 2, in <module>
    import _cffi_backend
ModuleNotFoundError: No module named '_cffi_backend'

**Comment by TrNullFree** [comment]
Solved! 
I have both python 3.10 and 3.11 
cffi was installed for 3.10, but not for 3.11.
And did this from read-en.txt:
_*.py files from this directory should be copied to the directory:
~/.config/far2l/plugins/python - The default directory for python plugins from which they can be easily activated._
