### ISSUE TITLE
python plugin crashes

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1818]
@m32 
python plugin crashes far2l (PANIC) on any call of python scripts from F11. 
To reproduce:
	py:load ucharmap
	F11
	select from plugins menu "Python Character Map"
far2l shows PANIC and crashes.

far2l version 2.5.2-6b3db4f0-beta Linux x86_64 - fresh today build from master with -DVIRTUAL_PYTHON

```
far2l 2.5.2-6b3db4f0-beta x64
Signal 0B [0000000000000060] on 0000000064F1DCA3
00000000FFFFFFFF 0000000000000000 00007F8A5C056DC0 00007F8A5C6422F8
00007F8A4FFFEA90 0000000000000000 00007F8A4FFFD360 00007F8A4CCF4AB0
00007F8A4D7389A8 00007F8A4FFFD2EC 0000000000000000 00007F8A4D7389A8
0000000000000000 0000000000000000 0000000000000000 00007F8A4FFFD2F8
00007F8A4D115882 0000000000010202 002B000000000033 0000000000000004
000000000000000E 0000000000000000 0000000000000060 00007F8A4FFFC7C0
00007F8A4CB34180 00007F8A4CE72BB0 00007F8A4CE73970 00007F8A4CE85490
0000000000000002 */$((*,")&/,-+)' -#,#+/$.#(.%/,%/ **+*+'!#*,$0!&/'
/usr/local/bin/far2l(+0x1a4bbf)[0x558d1f738bbf]
/lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0)[0x7f8a63a3c4b0]
/lib/x86_64-linux-gnu/libpython3.11.so.1.0(PyErr_Occurred+0x12)[0x7f8a4d115882]
/usr/local/lib/far2l/Plugins/python/plug/python.far-plug-wide(ProcessDialogEventW+0x70)[0x7f8a5c6495c0]
/usr/local/bin/far2l(+0x17382a)[0x558d1f70782a]
/usr/local/bin/far2l(+0x58348)[0x558d1f5ec348]
/usr/local/bin/far2l(+0x5dd82)[0x558d1f5f1d82]
/usr/local/bin/far2l(+0x5f553)[0x558d1f5f3553]
/usr/local/bin/far2l(+0x16c53a)[0x558d1f70053a]
/lib/x86_64-linux-gnu/libffi.so.8(+0x78b6)[0x7f8a613888b6]
/lib/x86_64-linux-gnu/libffi.so.8(+0x434d)[0x7f8a6138534d]
/lib/x86_64-linux-gnu/libffi.so.8(ffi_call+0x123)[0x7f8a61387f33]
/usr/lib/python3/dist-packages/_cffi_backend.cpython-311-x86_64-linux-gnu.so(+0x14e39)[0x7f8a4d7dde39]
/lib/x86_64-linux-gnu/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x81)[0x7f8a4d1786c1]

```

**Comment by m32** [comment]
Not every time a python plugin is created correctly, cmake/make copies files betwen python source and build/install directory and maybe you have a mismatch between c code and python code. Sometimes it helps me to run these commands:
#!/bin/bash
rm build/*
rm -rf build/python
rm -rf build/install/Plugins/python

**Comment by atolismesh** [comment]
@m32 

Did as you suggest. Didn't help. 
Also did :
rm -rf buld
sudo rm -rf /usr/local/lib/far2l
sudo rm -rf /usr/local/share/far2l
cmake -DUSEWX=yes  -DCMAKE_BUILD_TYPE=Release -DVIRTUAL_PYTHON=python3.11 -DVIRTUAL_PYTHON_VERSION=3.11  .. 
Same result - far2l shows PANIC and crashes.

**Comment by atolismesh** [comment]
Here is backtrace from gdb 
```
Thread 6 "far2l" received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x00007fffcf715882 in PyErr_Occurred () at /lib/x86_64-linux-gnu/libpython3.11.so.1.0
#1  0x00007fffe82265c9 in ProcessDialogEventW(int, void*) (Event=0, Param=0x7ffff0e16e70) at /home/user/git-oth/far2l/python/src/python.cpp:438
#2  0x00005555557f2904 in PluginW::ProcessDialogEvent(int, void*) (this=0x7fffe02c5120, Event=0, Param=0x7ffff0e16e70) at /home/user/git-oth/far2l/far2l/src/plug/PluginW.cpp:769
#3  0x00005555557e5585 in PluginManager::ProcessDialogEvent(int, void*) (this=0x7ffff0e18950, Event=0, Param=0x7ffff0e16e70)
    at /home/user/git-oth/far2l/far2l/src/plug/plugins.cpp:767
#4  0x0000555555639706 in Dialog::DlgProc(void*, int, int, long) (this=0x7fffe04593e0, hDlg=0x7fffe04593e0, Msg=4108, Param1=1, Param2=0)
    at /home/user/git-oth/far2l/far2l/src/dialog.cpp:4406
#5  0x000055555562a3b2 in Dialog::InitDialog() (this=0x7fffe04593e0) at /home/user/git-oth/far2l/far2l/src/dialog.cpp:509
#6  0x0000555555638e6b in Dialog::Process() (this=0x7fffe04593e0) at /home/user/git-oth/far2l/far2l/src/dialog.cpp:4233
#7  0x00005555557d0b4c in FarDialogRunSynched(HANDLE) (hDlg=0x7fffe04593e0) at /home/user/git-oth/far2l/far2l/src/plug/plugapi.cpp:1051
#8  0x00005555557de078 in std::__invoke_impl<int, int (*&)(void*), void*&>(std::__invoke_other, int (*&)(void*), void*&)
    (__f=@0x7ffff0e17140: 0x5555557d0adc <FarDialogRunSynched(HANDLE)>) at /usr/include/c++/12/bits/invoke.h:61
#9  0x00005555557dc078 in std::__invoke<int (*&)(void*), void*&>(int (*&)(void*), void*&) (__fn=@0x7ffff0e17140: 0x5555557d0adc <FarDialogRunSynched(HANDLE)>)
    at /usr/include/c++/12/bits/invoke.h:96
#10 0x00005555557d9fb3 in std::_Bind<int (*(void*))(void*)>::__call<int, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x7ffff0e17140, __args=...)
    at /usr/include/c++/12/functional:495
#11 0x00005555557d8087 in std::_Bind<int (*(void*))(void*)>::operator()<, int>() (this=0x7ffff0e17140) at /usr/include/c++/12/functional:580
#12 0x00005555557d5f1b in InterThreadCall<int, -1, std::_Bind<int (*(void*))(void*)> >(std::_Bind<int (*(void*))(void*)>) (fn=...)
    at /home/user/git-oth/far2l/far2l/src/base/InterThreadCall.hpp:102
#13 0x00005555557d0d35 in FarDialogRun(void*) (hDlg=0x7fffe04593e0) at /home/user/git-oth/far2l/far2l/src/plug/plugapi.cpp:1084
#14 0x00007ffff51db8b6 in  () at /lib/x86_64-linux-gnu/libffi.so.8
#15 0x00007ffff51d834d in  () at /lib/x86_64-linux-gnu/libffi.so.8
#16 0x00007ffff51daf33 in ffi_call () at /lib/x86_64-linux-gnu/libffi.so.8
#17 0x00007fffe805be39 in  () at /usr/lib/python3/dist-packages/_cffi_backend.cpython-311-x86_64-linux-gnu.so
#18 0x00007fffcf7786c1 in _PyObject_MakeTpCall () at /lib/x86_64-linux-gnu/libpython3.11.so.1.0
#19 0x00007fffcf70bbb7 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.11.so.1.0
#20 0x00007fffcf868d82 in  () at /lib/x86_64-linux-gnu/libpython3.11.so.1.0
#21 0x00007fffcf77be28 in  () at /lib/x86_64-linux-gnu/libpython3.11.so.1.0
#22 0x00007fffe8225a1f in PythonHolder::vcall(char const*, int, ...) (this=0x7fffe02a6f70, func=0x7fffe822a108 "OpenPlugin", n=2)
    at /home/user/git-oth/far2l/python/src/python.cpp:278
#23 0x00007fffe8225c9d in OpenPluginW(int, INT_PTR) (OpenFrom=1, Item=0) at /home/user/git-oth/far2l/python/src/python.cpp:352
#24 0x00005555557f253b in PluginW::OpenPlugin(int, long) (this=0x7fffe02c5120, OpenFrom=1, Item=0) at /home/user/git-oth/far2l/far2l/src/plug/PluginW.cpp:647
#25 0x00005555557eab73 in PluginManager::OpenPlugin(Plugin*, int, long) (this=0x7ffff0e18950, pPlugin=0x7fffe02c5120, OpenFrom=1, Item=0)
    at /home/user/git-oth/far2l/far2l/src/plug/plugins.cpp:1747
#26 0x00005555557e855f in PluginManager::CommandsMenu(int, int, wchar_t const*) (this=0x7ffff0e18950, ModalType=1, StartPos=0, HistoryName=0x0)
    at /home/user/git-oth/far2l/far2l/src/plug/plugins.cpp:1362
#27 0x00005555556eda9b in Manager::PluginsMenu() (this=0x7fffe002b340) at /home/user/git-oth/far2l/far2l/src/manager.cpp:988
#28 0x00005555556ed30b in Manager::ProcessKey(unsigned int) (this=0x7fffe002b340, Key=65658) at /home/user/git-oth/far2l/far2l/src/manager.cpp:807
#29 0x00005555556eceab in Manager::ProcessMainLoop() (this=0x7fffe002b340) at /home/user/git-oth/far2l/far2l/src/manager.cpp:667
#30 0x00005555556eccb9 in Manager::EnterMainLoop() (this=0x7fffe002b340) at /home/user/git-oth/far2l/far2l/src/manager.cpp:631
#31 0x00005555556e9580 in MainProcess(FARString, FARString, FARString, int, int) (strEditViewArg=..., strDestName1=..., strDestName2=..., StartLine=-1, StartChar=-1)
    at /home/user/git-oth/far2l/far2l/src/main.cpp:319
#32 0x00005555556eab56 in FarAppMain(int, char**) (argc=1, argv=0x555555a89860) at /home/user/git-oth/far2l/far2l/src/main.cpp:628
#33 0x00007ffff7b92916 in WinPortAppThread::Entry() (this=0x555555bb8b10) at /home/user/git-oth/far2l/WinPort/src/Backend/WX/wxMain.cpp:62
#34 0x00007ffff65801dc in  () at /lib/x86_64-linux-gnu/libwx_baseu-3.2.so.0
#35 0x00007ffff788f18a in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#36 0x00007ffff791dbd0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

```

**Comment by m32** [comment]
-DVIRTUAL_PYTHON=/devel/bin/python3/bin/python
this parameter requires the full path to the executable python program (pythonX.XX.so uses it to set PYTHONPATH), also this is a way to use virtualenv without activating it with activate
Can You try again with python version 3.8 or 3.9 - I didn't run far2l with python 3.11

**Comment by m32** [comment]
ProcessDialogEvent is handled by the plugin manager and passed to each loaded plugin. Change the handling in pluginmanager.py:def ProcessDialogEvent and log the exception that appears there log.exception('xxx')

**Comment by atolismesh** [comment]
Changed pluginmanager.py
```
    def ProcessDialogEvent(self, Event, Param):
        for plugin in self.plugins:
            rc = plugin.Plugin.ProcessDialogEvent(self, self.info, ffi, ffic, Event, Param)
            log.exception("xxxxxx ")
            if rc:
                return rc
        return 0

```
Got same exception and this lines in /tmp/far2l-py:
```
2023-09-04 23:26:20,466 pluginmanager:213:DEBUG: cmd:load ucharmap
2023-09-04 23:26:20,466 pluginmanager:79:DEBUG: install plugin: ucharmap
2023-09-04 23:26:24,203 pluginmanager:187:DEBUG: GetPluginInfo
2023-09-04 23:26:24,204 pluginmanager:187:DEBUG: GetPluginInfo
2023-09-04 23:26:26,419 pluginmanager:210:DEBUG: OpenPlugin(1, 0)
2023-09-04 23:26:26,420 pluginmanager:127:DEBUG: pluginGetFrom(1 (PLUGINSMENU), 0)
2023-09-04 23:26:26,420 pluginmanager:130:DEBUG: pluginGetFrom(openok=True, no=0 : ucharmap)
2023-09-04 23:26:26,463 pluginmanager:282:ERROR: xxxxxx 
NoneType: None

```

**Comment by m32** [comment]
gdb indicates that this problem is in InitDialog and I'm not really sure why.

What I read from the logs:
- python plugin loads properly and ucharmap py:load loads correctly
- you have only ucharmap loaded
- 22 in gdb means that far2l by F11 starts plugin launch
- 13 (gdb) informs about starting a dialogue
- 5 (gdb) informs about dialogue initialization
- 1 (gdb) means that the support is in python again
- log entry xxxx means python didn't crash in ProcessDialogEvent handler

please use try/except around the whole method and log the result:
def _ProcessDialogEvent..... <- renamed current code
def ProcessDialogEvent...: <- new wrapper code
    try:
       return self._ProcessDialogEvent...
    except:
       log.exception('ProcessDialogEvent')
    return 0

just to be sure, change line with:
rc = plugin.OpenPlugin(OpenFrom)

try:
    rc = plugin.OpenPlugin(OpenFrom)
except:
    log.exception('OpenPlugin')
    return None

Can you check if python 3.8 (<3.11) is working properly?
Did you compile the cffi library yourself, or did you get it from a ready-made package?

**Comment by atolismesh** [comment]
1. I modifies code in pluginmanager.py as you suggest + faulthandler.
```
    def _ProcessDialogEvent(self, Event, Param):
        log.exception('xxx2')
        faulthandler.dump_traceback(fault_out)
        for plugin in self.plugins:
            rc = plugin.Plugin.ProcessDialogEvent(self, self.info, ffi, ffic, Event, Param)
            log.exception('xxx3')
            faulthandler.dump_traceback(fault_out)
            if rc:
                return rc
        return 0

    def ProcessDialogEvent(self, Event, Param):
        log.exception('xxx1')
        try:
            return self._ProcessDialogEvent(Event, Param)
        except:
            log.exception('ProcessDialogEvent')
        return 0


```
Now get this output: 
```
2023-09-05 17:51:24,501 pluginmanager:29:DEBUG: ******************** start
2023-09-05 17:51:24,501 pluginmanager:30:DEBUG: sys.path=['/usr/lib/python311.zip', '/usr/local/lib/far2l/Plugins/python/plug/plugins', '/usr/local/lib/far2l/Plugins/python/plug', '/home/user/.config/far2l/plugins/python', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/local/lib/far2l/Plugins/python/plug/python/lib/python3.11/site-packages', '/home/user/.local/lib/python3.11/site-packages', '/usr/local/lib/python3.11/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.11/dist-packages']
2023-09-05 17:51:24,501 pluginmanager:31:DEBUG: userhome=/home/user/.config/far2l/plugins/python
2023-09-05 17:51:30,444 pluginmanager:65:DEBUG: SetStartupInfo(7FF544FD24E0)
2023-09-05 17:51:30,477 pluginmanager:190:DEBUG: GetPluginInfo
2023-09-05 17:51:32,424 pluginmanager:190:DEBUG: GetPluginInfo
2023-09-05 17:51:32,424 pluginmanager:213:DEBUG: OpenPlugin(4, 140691120987356)
2023-09-05 17:51:32,435 pluginmanager:216:DEBUG: cmd:load ucharmap
2023-09-05 17:51:32,435 pluginmanager:82:DEBUG: install plugin: ucharmap
2023-09-05 17:52:08,646 pluginmanager:190:DEBUG: GetPluginInfo
2023-09-05 17:52:08,647 pluginmanager:190:DEBUG: GetPluginInfo
2023-09-05 17:52:09,903 pluginmanager:213:DEBUG: OpenPlugin(1, 0)
2023-09-05 17:52:09,903 pluginmanager:130:DEBUG: pluginGetFrom(1 (PLUGINSMENU), 0)
2023-09-05 17:52:09,903 pluginmanager:133:DEBUG: pluginGetFrom(openok=True, no=0 : ucharmap)
2023-09-05 17:52:09,942 pluginmanager:294:ERROR: xxx1
NoneType: None
2023-09-05 17:52:09,943 pluginmanager:283:ERROR: xxx2
NoneType: None
2023-09-05 17:52:09,943 pluginmanager:287:ERROR: xxx3
NoneType: None

``` 
faultlog: 
```
Current thread 0x00007ff54694f6c0 (most recent call first):
  File "/usr/local/lib/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 284 in _ProcessDialogEvent
  File "/usr/local/lib/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 296 in ProcessDialogEvent
  File "/home/user/.config/far2l/plugins/python/ucharmap.py", line 426 in OpenPlugin
  File "/usr/local/lib/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 254 in OpenPlugin
Current thread 0x00007ff54694f6c0 (most recent call first):
  File "/usr/local/lib/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 288 in _ProcessDialogEvent
  File "/usr/local/lib/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 296 in ProcessDialogEvent
  File "/home/user/.config/far2l/plugins/python/ucharmap.py", line 426 in OpenPlugin
  File "/usr/local/lib/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 254 in OpenPlugin
Fatal Python error: Segmentation fault

Current thread 0x00007ff54694f6c0 (most recent call first):
  File "/home/user/.config/far2l/plugins/python/ucharmap.py", line 426 in OpenPlugin
  File "/usr/local/lib/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 254 in OpenPlugin

Extension modules: _cffi_backend (total: 1)
Fatal Python error: Aborted

Current thread 0x00007ff54694f6c0 (most recent call first):
  File "/home/user/.config/far2l/plugins/python/ucharmap.py", line 426 in OpenPlugin
  File "/usr/local/lib/far2l/Plugins/python/plug/far2l/pluginmanager.py", line 254 in OpenPlugin

Extension modules: _cffi_backend (total: 1)

```
2.  Now trying to install python3.8 and recompile far2l
3. The cffi library -  from a ready-made package (python3.11.4)

**Comment by m32** [comment]
ucharmap.py:426 => res = self.info.DialogRun(hDlg)

in my version of ubuntu (20.4) cffi is not compatible with python 3.8.10, I recompiled it and everything works without problems

**Comment by atolismesh** [comment]
Installed python3.8.18, recompiled cffi 1.15.1 library myself. It wasn't easy.
Now python plugin works as expected.
Thank you very much @m32 !

Now I will try to revert back to python 3.11.
And I'll try to understand what happened to my python 3.11 in the last 2 weeks. 
But I also saw the same problem reported by another person.

**Comment by m32** [comment]
compiling with python with virtualphthon is simpler and at the same time more complicated.

from prebuild.sh:
"$DST/python/bin/python" -m pip install --force-reinstall --no-binary :all: cffi

i.e. cffi is recompiled from sources, not from a package

**Comment by atolismesh** [comment]
Reverted back to python 3.11.
The same trick does not work with  python 3.11 :-(

**Comment by atolismesh** [comment]
Compiling with virtualphthon 3.11.4 doesn't solve the problem.
far2l keeps showing PANIC and crashes

**Comment by m32** [comment]
i installed debian 12.1 with python 3.11 and it doesn't work as you describe, without debugging through gdb and looking at libffi, finding the reason is hard.

FFI is cool because it's easy, but I don't feel any control over the generated wrappers - I've been dreaming of a library based on ctypes for some time, apparently it's time to implement it.

**Comment by atolismesh** [comment]
Your help and efforts are greatly appreciated!

I also tested Manjaro (rolling update)  with python 3.11.3, 3.11.5 - same bad results.

**Comment by m32** [comment]
https://github.com/elfmz/far2l/pull/1834 resolves this issue

**Comment by atolismesh** [comment]
Great! 
python plugin works now as expected
