### ISSUE TITLE
Segmentation fault on RAR archive with password opening

### ISSUE THREAD

**Issue by h4tr3d** [elfmz/far2l#395]
Try to open any RAR archive protected with password.

Stack trace:
```
#0  0x0000000000000000 in  ()
#1  0x00007fffebcf8fd9 in CallbackProc(unsigned int, long, long, long) (msg=<optimized out>, UserData=<optimized out>, P1=140737238383488, P2=128) at /usr/src/debug/far2l/multiarc/src/formats/rar/rar.cpp:90
#2  0x00007fffebd2c050 in Archive::RequestArcPassword() (this=this@entry=0x7fffeac299e0) at /usr/src/debug/far2l/multiarc/src/formats/rar/unrar/arcread.cpp:879
#3  0x00007fffebd2c738 in Archive::ReadHeader15() (this=0x7fffeac299e0) at /usr/src/debug/far2l/multiarc/src/formats/rar/unrar/arcread.cpp:125
#4  0x00007fffebd2eba8 in Archive::ReadHeader() (this=this@entry=0x7fffeac299e0) at /usr/src/debug/far2l/multiarc/src/formats/rar/unrar/arcread.cpp:22
#5  0x00007fffebd2ebf1 in Archive::SearchBlock(HEADER_TYPE) (this=this@entry=0x7fffeac299e0, HeaderType=HeaderType@entry=HEAD_FILE) at /usr/src/debug/far2l/multiarc/src/formats/rar/unrar/arcread.cpp:41
#6  0x00007fffebd1d852 in RARReadHeaderEx(void*, RARHeaderDataEx*) (hArcData=0x7fffeac13010, D=D@entry=0x7fffebd79fc0 <HeaderData>) at /usr/src/debug/far2l/multiarc/src/formats/rar/unrar/dll.cpp:190
#7  0x00007fffebcf91f1 in RAR_GetArcItem(oldfar::PluginPanelItem*, ArcItemInfo*) (Item=0x7ffff119e870, Info=0x7ffff119e730) at /usr/src/debug/far2l/multiarc/src/formats/rar/rar.cpp:163
#8  0x00007fffebcf4fe4 in PluginClass::ReadArchive(char const*) (this=this@entry=0x7fffec10b2f0, Name=Name@entry=0x7fffec10b2f0 "/home/hatred/tmp/encrypted.rar")
    at /usr/src/debug/far2l/multiarc/src/arcread.cpp:98
#9  0x00007fffebcf5824 in PluginClass::ReadArchive(char const*) (this=0x7fffec10b2f0, Name=0x7fffec10b2f0 "/home/hatred/tmp/encrypted.rar") at /usr/src/debug/far2l/multiarc/src/arcread.cpp:75
#10 0x00007fffebcf5c3f in PluginClass::GetFindData(oldfar::PluginPanelItem**, int*, int) (this=0x7fffec10b2f0, pPanelItem=0x7fffec07c2c0, pItemsNumber=0x7ffff11a125c, OpMode=<optimized out>)
    at /usr/src/debug/far2l/multiarc/src/arcread.cpp:289
#11 0x00005555556e5634 in PluginA::GetFindData(void*, PluginPanelItem**, int*, int) (this=0x7fffec07c180, hPlugin=<optimized out>, pPanelItem=0x7ffff11a1278, pItemsNumber=0x7ffff11a125c, OpMode=<optimized out>)
    at /usr/src/debug/far2l/far2l/PluginA.cpp:1100
#12 0x000055555568321c in PluginManager::GetFindData(void*, PluginPanelItem**, int*, int)
    (this=this@entry=0x7ffff11a8878, hPlugin=0x7fffec0675a0, pPanelData=pPanelData@entry=0x7ffff11a1278, pItemsNumber=pItemsNumber@entry=0x7ffff11a125c, OpMode=OpMode@entry=0)
    at /usr/src/debug/far2l/far2l/plugins.cpp:947
#13 0x0000555555636bb9 in FileList::UpdatePlugin(int, int) (this=0x7fffec04e370, KeepSelection=0, IgnoreVisible=<optimized out>) at /usr/src/debug/far2l/far2l/flupdate.cpp:682
#14 0x00005555556391aa in FileList::Update(int) (this=0x7fffec04e370, Mode=0) at /usr/src/debug/far2l/far2l/flupdate.cpp:88
#15 0x0000555555611708 in FileList::OpenFilePlugin(wchar_t const*, int, OPENFILEPLUGINTYPE) (this=0x7fffec04e370, FileName=0x7fffec0fc6d0 L"encrypted.rar", PushPrev=<optimized out>, Type=<optimized out>)
    at /usr/src/debug/far2l/far2l/filelist.cpp:4635
#16 0x0000555555611e7e in FileList::ProcessEnter(bool, bool, bool, bool, OPENFILEPLUGINTYPE)
    (this=0x7fffec04e370, EnableExec=<optimized out>, SeparateWindow=<optimized out>, EnableAssoc=<optimized out>, RunAs=<optimized out>, Type=OFP_NORMAL) at /usr/src/debug/far2l/far2l/UnicodeString.hpp:186
#17 0x000055555561758f in FileList::ProcessKey(int) (this=0x7fffec04e370, Key=13) at /usr/src/debug/far2l/far2l/filelist.cpp:1281
#18 0x000055555561b53e in FilePanels::ProcessKey(int) (this=0x7fffec04fb20, Key=13) at /usr/src/debug/far2l/far2l/filepanels.cpp:778
#19 0x000055555566e191 in Manager::ProcessKey(unsigned int) (this=this@entry=0x7fffec002b40, Key=<optimized out>) at /usr/src/debug/far2l/far2l/manager.cpp:1145
#20 0x000055555566e91a in Manager::ProcessKey(unsigned int) (Key=<optimized out>, this=0x7fffec002b40) at /usr/src/debug/far2l/far2l/manager.cpp:779
#21 0x000055555566e91a in Manager::ProcessMainLoop() (this=0x7fffec002b40) at /usr/src/debug/far2l/far2l/manager.cpp:717
#22 0x000055555566eb31 in Manager::EnterMainLoop() (this=0x7fffec002b40) at /usr/src/debug/far2l/far2l/manager.cpp:678
#23 0x000055555566accd in MainProcess(wchar_t const*, wchar_t const*, wchar_t const*, wchar_t const*, int, int)
    (lpwszEditName=<optimized out>, lpwszViewName=<optimized out>, lpwszDestName1=<optimized out>, lpwszDestName2=<optimized out>, StartLine=<optimized out>, StartChar=-1)
    at /usr/src/debug/far2l/far2l/main.cpp:285
#24 0x000055555566b532 in MainProcessSEH(UnicodeString&, UnicodeString&, UnicodeString&, UnicodeString&, int, int) (StartChar=-1, StartLine=-1, DestName2=..., DestName1=..., strViewName=..., strEditName=...)
    at /usr/src/debug/far2l/far2l/UnicodeString.hpp:186
#25 0x000055555566b532 in FarAppMain(int, char**) (argc=1, argv=0x7fffffffdee8) at /usr/src/debug/far2l/far2l/main.cpp:586
#26 0x000055555570f95e in WinPortAppThread::Entry() (this=0x555555b459d0) at /usr/src/debug/far2l/WinPort/src/UI/Main.cpp:56
#27 0x00007ffff783953a in wxThread::CallEntry() () at /usr/lib/libwx_baseu-3.0.so.0
#28 0x00007ffff783d1f5 in  () at /usr/lib/libwx_baseu-3.0.so.0
#29 0x00007ffff720aa9d in start_thread () at /usr/lib/libpthread.so.0
#30 0x00007ffff713ab23 in clone () at /usr/lib/libc.so.6
```

**Comment by h4tr3d** [comment]
Protected RAR sample can be taken from: https://midnight-commander.org/ticket/1685
