### ISSUE TITLE
copy-pasting text from libreoffice writer to far2l makes far2l hang

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#557]
LibreOffice: 6.0.7.3
build ID: 1:6.0.7-0ubuntu0.18.04.6

Far Manager, version 2.2 (build 19/06/23-796809f-alpha) Linux x86_64

Linux Mint 19.1 amd64

**Comment by unxed** [comment]
![Снимок экрана в 2019-06-25 12-30-10](https://user-images.githubusercontent.com/1151423/60087109-05f52400-9745-11e9-99e1-de64f28b828a.png)

**Comment by elfmz** [comment]
for me pasting works perfectly, however bug may be similar to https://github.com/elfmz/far2l/issues/125

**Comment by elfmz** [comment]
can you do following:
- gdb far2l
- type 'run' in gdb console -> far2l will be launched
- repro issue
- return back to gdb console, hit ctrl+c then type 'thread apply all bt' and send what will be printed out there

**Comment by unxed** [comment]
```
(gdb) run
Starting program: /usr/bin/far2l 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
argv[0]='/usr/bin/far2l' g_strFarModuleName='/usr/lib/far2l/far2l' translation_prefix=''

[New Thread 0x7fffed60d700 (LWP 11652)]
[New Thread 0x7fffeb0b6700 (LWP 11653)]
[New Thread 0x7fffea863700 (LWP 11654)]
[New Thread 0x7fffea062700 (LWP 11655)]
[New Thread 0x7fffe2a67700 (LWP 11656)]
[New Thread 0x7fffe2266700 (LWP 11657)]
[New Thread 0x7fffe160b700 (LWP 11658)]
[New Thread 0x7fffe0e0a700 (LWP 11659)]
^C
Thread 1 "far2l" received signal SIGINT, Interrupt.
0x00007ffff5dbfbf9 in __GI___poll (fds=0x555555dc5530, nfds=3, timeout=500)
    at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: Нет такого файла или каталога.
(gdb) thread apply all bt

Thread 9 (Thread 0x7fffe0e0a700 (LWP 11659)):
#0  0x00007ffff5dbfbf9 in __GI___poll (fds=0x7fffdc01b710, nfds=2, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6a274c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6a27862 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff2bdf026 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff6a4ef15 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff6cf86db in start_thread (arg=0x7fffe0e0a700)
    at pthread_create.c:463
#6  0x00007ffff5dcc88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fffe160b700 (LWP 11658)):
#0  0x00007ffff5dbfbf9 in __GI___poll (fds=0x7fffdc00d6b0, nfds=1, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6a274c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6a275dc in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6a27621 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff6a4ef15 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff6cf86db in start_thread (arg=0x7fffe160b700)
---Type <return> to continue, or q <return> to quit---
   463
#6  0x00007ffff5dcc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffe2266700 (LWP 11657)):
#0  0x00007ffff6cfef85 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fffe2265a80, expected=0, futex_word=0x7fffe303d7f8 <GvfsServiceMonitor::m_instance+152>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x00007ffff6cfef85 in __pthread_cond_wait_common (abstime=0x7fffe2265a80, mutex=0x7fffe303d7a8 <GvfsServiceMonitor::m_instance+72>, cond=0x7fffe303d7d0 <GvfsServiceMonitor::m_instance+112>) at pthread_cond_wait.c:539
#2  0x00007ffff6cfef85 in __pthread_cond_timedwait (cond=0x7fffe303d7d0 <GvfsServiceMonitor::m_instance+112>, mutex=0x7fffe303d7a8 <GvfsServiceMonitor::m_instance+72>, abstime=0x7fffe2265a80) at pthread_cond_wait.c:667
#3  0x00007fffe2e250fa in GvfsServiceMonitor::worker() () at /usr/lib/far2l/Plugins/gvfspanel/plug/gvfspanel.far-plug-wide
#4  0x00007ffff670f66f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6cf86db in start_thread (arg=0x7fffe2266700) at pthread_create.c:463
#6  0x00007ffff5dcc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fffe2a67700 (LWP 11656)):
#0  0x00007ffff5dc6839 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff6a6d4af in g_cond_wait () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6a26775 in g_main_context_wait () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6a27803 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fffe2e256e6 in GvfsServiceMonitor::loop() () at /usr/lib/far2l/Plugins/gvfspanel/plug/gvfspanel.far-plug-wide
#5  0x00007ffff670f66f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6cf86db in start_thread (arg=0x7fffe2a67700) at pthread_create.c:463
#7  0x00007ffff5dcc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fffea062700 (LWP 11655)):
#0  0x00007ffff5dc203f in __GI___select (nfds=21, readfds=0x7fffea061910, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00005555556f4a66 in WinPortFSNotify::WatcherProc() ()
#2  0x00005555556f4b59 in WinPortFSNotify::sWatcherProc(void*) ()
#3  0x00007ffff6cf86db in start_thread (arg=0x7fffea062700) at pthread_create.c:463
#4  0x00007ffff5dcc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fffea863700 (LWP 11654)):
#0  0x00007ffff5dc203f in __GI___select (nfds=18, readfds=0x7fffea862910, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00005555556f4a66 in WinPortFSNotify::WatcherProc() ()
#2  0x00005555556f4b59 in WinPortFSNotify::sWatcherProc(void*) ()
#3  0x00007ffff6cf86db in start_thread (arg=0x7fffea863700) at pthread_create.c:463
#4  0x00007ffff5dcc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

---Type <return> to continue, or q <return> to quit---
Thread 3 (Thread 0x7fffeb0b6700 (LWP 11653)):
#0  0x00007ffff6cfe9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fffeb0b16b8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffff6cfe9f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x7fffeb0b1668, cond=0x7fffeb0b1690) at pthread_cond_wait.c:502
#2  0x00007ffff6cfe9f3 in __pthread_cond_wait (cond=0x7fffeb0b1690, mutex=0x7fffeb0b1668) at pthread_cond_wait.c:655
#3  0x00007ffff670986c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x000055555572594c in wxClipboardBackend::OnClipboardIsFormatAvailable(unsigned int) ()
#5  0x00005555556ef27b in WINPORT_IsClipboardFormatAvailable ()
#6  0x0000555555591b5a in Clipboard::PasteFormat(wchar_t const*) ()
#7  0x00005555555d6320 in Editor::Paste(wchar_t const*) ()
#8  0x00005555555d7eb9 in Editor::ProcessPasteEvent() [clone .part.30] ()
#9  0x00005555555e0f25 in Editor::ProcessKey(int) ()
#10 0x00005555555f469c in FileEditor::ReProcessKey(int, int) ()
#11 0x0000555555663c31 in Manager::ProcessKey(unsigned int) ()
#12 0x000055555566429a in Manager::ProcessMainLoop() ()
#13 0x0000555555664441 in Manager::EnterMainLoop() ()
#14 0x000055555566066b in MainProcess(wchar_t const*, wchar_t const*, wchar_t const*, wchar_t const*, int, int) ()
#15 0x0000555555660a43 in MainProcessSEH(UnicodeString&, UnicodeString&, UnicodeString&, UnicodeString&, int, int) ()
#16 0x0000555555661380 in FarAppMain(int, char**) ()
#17 0x0000555555722ece in WinPortAppThread::Entry() ()
#18 0x00007ffff70bed52 in wxThread::CallEntry() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#19 0x00007ffff70c663c in  () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#20 0x00007ffff6cf86db in start_thread (arg=0x7fffeb0b6700) at pthread_create.c:463
#21 0x00007ffff5dcc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffed60d700 (LWP 11652)):
#0  0x00007ffff5dc203f in __GI___select (nfds=8, readfds=0x7fffed60b9a0, writefds=0x0, exceptfds=0x7fffed60ba20, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000055555570b9f8 in SudoAskpassServer::Thread() ()
#2  0x000055555570c0b9 in SudoAskpassServer::sThread(void*) ()
#3  0x00007ffff6cf86db in start_thread (arg=0x7fffed60d700) at pthread_create.c:463
#4  0x00007ffff5dcc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7fb0280 (LWP 11648)):
#0  0x00007ffff5dbfbf9 in __GI___poll (fds=0x555555dc5530, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6a274c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6a27862 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff57231f6 in gtk_dialog_run () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#4  0x00007ffff76154c3 in wxGUIAppTraits::ShowAssertDialog(wxString const&) () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#5  0x00007ffff6f74ae1 in  () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#6  0x00007ffff6f774c7 in wxAppConsoleBase::OnAssertFailure(wchar_t const*, int, wchar_t const*, wchar_t const*, wchar_t const*) ()
---Type <return> to continue, or q <return> to quit---
    at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#7  0x00007ffff75e11a0 in wxApp::OnAssertFailure(wchar_t const*, int, wchar_t const*, wchar_t const*, wchar_t const*) ()
    at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#8  0x00007ffff6f777bf in  () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#9  0x00007ffff6f76a31 in wxOnAssert(char const*, int, char const*, char const*, wchar_t const*) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#10 0x00007ffff703e226 in wxString::FromAscii(char const*, unsigned long) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#11 0x00007ffff703e39c in wxString::FromAscii(char const*) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#12 0x00007ffff75f2230 in wxDataFormat::GetId() const () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#13 0x00007ffff75ee200 in  () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#14 0x00007ffff47d510d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff47e7fce in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff47f0685 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff47f1578 in g_signal_emit_by_name () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff57fc2e3 in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#19 0x00007ffff57ffe49 in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#20 0x00007ffff579b38b in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#21 0x00007ffff47d510d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff47e7d58 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff47f001f in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff47f109f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff58b12bc in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#26 0x00007ffff5799b03 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#27 0x00007ffff540f02c in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#28 0x00007ffff6a27317 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff6a27550 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff6a275dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff5798c41 in gtk_main_iteration () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#32 0x00007ffff75fcc45 in wxGUIEventLoop::YieldFor(long) () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#33 0x00007ffff75e6b2e in wxClipboard::DoIsSupported(wxDataFormat const&) () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#34 0x00007ffff75e71f1 in wxClipboard::IsSupported(wxDataFormat const&) () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#35 0x0000555555725803 in wxClipboardBackend::OnClipboardIsFormatAvailable(unsigned int) ()
#36 0x0000555555728092 in InMainCallerBase<std::_Bind<bool (wxClipboardBackend::*(wxClipboardBackend*, unsigned int))(unsigned int)> >::Callback() ()
#37 0x00007ffff70f39c1 in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#38 0x00007ffff70f3a13 in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#39 0x00007ffff70f3a75 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#40 0x00007ffff70f4be2 in wxEvtHandler::ProcessPendingEvents() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#41 0x00007ffff6f759e7 in wxAppConsoleBase::ProcessPendingEvents() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#42 0x00007ffff75dcbbd in wxApp::DoIdle() () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#43 0x00007ffff75dccc3 in  () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
---Type <return> to continue, or q <return> to quit---
#44 0x00007ffff6a27185 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007ffff6a27550 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff6a27862 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff5798a37 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#48 0x00007ffff75fcb05 in wxGUIEventLoop::DoRun() () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#49 0x00007ffff6fafa93 in wxEventLoopBase::Run() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#50 0x00007ffff6f770a6 in wxAppConsoleBase::MainLoop() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#51 0x00007ffff7001ae9 in wxEntry(int&, wchar_t**) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#52 0x0000555555722b71 in WinPortMainWX(int, char**, int (*)(int, char**), int*) ()
#53 0x000055555570c9a9 in WinPortMain ()
#54 0x00007ffff5cccb97 in __libc_start_main (main=
    0x55555558e2a0 <main>, argc=1, argv=0x7fffffffdf58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf48)
    at ../csu/libc-start.c:310
#55 0x00005555555909ca in _start ()
(gdb) 
```

**Comment by elfmz** [comment]
known wx bug, see: https://github.com/elfmz/far2l/issues/254

**Comment by unxed** [comment]
Там пишут:

> Там есть слова о том, что можно сделать в своем коде, дабы их побороть.

Может, можно workaround какой придумать? Переставлять язык либры из-за фара, ну, странно :)

**Comment by elfmz** [comment]
try on branch wx-assert-handler

**Comment by unxed** [comment]
Tried, works like a charm!

**Comment by unxed** [comment]
Should I close this now?
