### ISSUE TITLE
netrocks hangs

### ISSUE THREAD

**Issue by asimonov-hitachi** [elfmz/far2l#567]
great work on netrocks/sftp!
I cannot live without it now :)

but something is not quite working with slow/broken connections.
i am connecting to google cloud machine and sometimes netrocks just hangs.
in fact entire far2l on ubuntu 18 is not responding.

here is what i see running when this happens:

```
$ ps -elf | grep far2l
0 S alexey   15305  2742  0  80   0 - 13589 poll_s 19:38 ?        00:00:00 /usr/local/lib/far2l/Plugins/NetRocks/plug/NetRocks-SFTP.broker 23 33
0 S alexey   15600 15368  0  80   0 -  5384 pipe_w 19:43 pts/0    00:00:00 grep --color=auto far2l
0 S alexey   26342  2742  0  80   0 - 247972 poll_s 15:03 ?       00:01:17 far2l
```

if I kill broker it re-spawns and everything keeps hanging.
until i kill far2l

**Comment by elfmz** [comment]
please run far2l under gdb by executing in terminal:

> gdb far2l

then type in gdb console: 

> run

After that reproduce issue in opened far2l window, and once far2l hang, switch back to terminal with gdb, then hit Ctrl+C there and type following command:

> thread apply all bt

..and report its output

**Comment by asimonov-hitachi** [comment]
great!

when I started far2l from gdb I could not reproduce the problem.

but managed to start far2l standalone and reproduce.
then attached 'gdb -p PID' and got this:

```
(gdb) thread apply all bt

Thread 6 (Thread 0x7f47ca7fc700 (LWP 18815)):
#0  0x00007f47ddc9b03f in __GI___select (nfds=23, readfds=0x7f47ca7fb910, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000558b49f9ba66 in WinPortFSNotify::WatcherProc() ()
#2  0x0000558b49f9bb59 in WinPortFSNotify::sWatcherProc(void*) ()
#3  0x00007f47debd26db in start_thread (arg=0x7f47ca7fc700)
    at pthread_create.c:463
#4  0x00007f47ddca588f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f47caffd700 (LWP 18814)):
#0  0x00007f47ddc9b03f in __GI___select (nfds=30, readfds=0x7f47caff4b10, writefds=0x0, exceptfds=0x7f47caff4b90, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00007f47c912cb1a in IPCRecver::Recv(void*, unsigned long) ()
    at /usr/local/lib/far2l/Plugins/NetRocks/plug/NetRocks.far-plug-wide
#2  0x00007f47c912ed90 in HostRemote::RecvReply(IPCCommand) ()
    at /usr/local/lib/far2l/Plugins/NetRocks/plug/NetRocks.far-plug-wide
#3  0x00007f47c912efa0 in HostRemote::IsBroken() ()
    at /usr/local/lib/far2l/Plugins/NetRocks/plug/NetRocks.far-plug-wide
#4  0x00007f47c9122e72 in PluginImpl::ValidateConnection() ()
    at /usr/local/lib/far2l/Plugins/NetRocks/plug/NetRocks.far-plug-wide
---Type <return> to continue, or q <return> to quit---
#5  0x00007f47c912300f in PluginImpl::GetFindData(PluginPanelItem**, int*, int) () at /usr/local/lib/far2l/Plugins/NetRocks/plug/NetRocks.far-plug-wide
#6  0x0000558b49f2327e in PluginManager::GetFindData(void*, PluginPanelItem**, int*, int) ()
#7  0x0000558b49ed2f15 in FileList::UpdatePlugin(int, int) ()
#8  0x0000558b49ed5812 in FileList::Update(int) ()
#9  0x0000558b49ea9b58 in FileList::ChangeDir(wchar_t const*, int) ()
#10 0x0000558b49eabe19 in FileList::ProcessEnter(bool, bool, bool, bool, OPENFILEPLUGINTYPE) ()
#11 0x0000558b49eb183a in FileList::ProcessKey(int) ()
#12 0x0000558b49eb5e6e in FilePanels::ProcessKey(int) ()
#13 0x0000558b49f0ac31 in Manager::ProcessKey(unsigned int) ()
#14 0x0000558b49f0b29a in Manager::ProcessMainLoop() ()
#15 0x0000558b49f0b441 in Manager::EnterMainLoop() ()
#16 0x0000558b49f0766b in MainProcess(wchar_t const*, wchar_t const*, wchar_t const*, wchar_t const*, int, int) ()
#17 0x0000558b49f07a43 in MainProcessSEH(UnicodeString&, UnicodeString&, UnicodeString&, UnicodeString&, int, int) ()
#18 0x0000558b49f08380 in FarAppMain(int, char**) ()
#19 0x0000558b49fc9f1e in WinPortAppThread::Entry() ()
#20 0x00007f47def98d52 in wxThread::CallEntry() ()
    at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#21 0x00007f47defa063c in  () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#22 0x00007f47debd26db in start_thread (arg=0x7f47caffd700)
    at pthread_create.c:463
#23 0x00007f47ddca588f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f47d08a8700 (LWP 18810)):
#0  0x00007f47ddc98bf9 in __GI___poll (fds=0x558b4acddd30, nfds=3, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f47de9005c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f47de900962 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f47daab80e6 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f47de928195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#5  0x00007f47debd26db in start_thread (arg=0x7f47d08a8700)
    at pthread_create.c:463
#6  0x00007f47ddca588f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f47d10a9700 (LWP 18809)):
#0  0x00007f47ddc98bf9 in __GI___poll (fds=0x558b4accc040, nfds=2, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f47de9005c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f47de9006dc in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f47de900721 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f47de928195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f47debd26db in start_thread (arg=0x7f47d10a9700)
    at pthread_create.c:463
#6  0x00007f47ddca588f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f47d4f27700 (LWP 18808)):
#0  0x00007f47ddc9b03f in __GI___select (nfds=8, readfds=0x7f47d4f259a0, writefds=0x0, exceptfds=0x7f47d4f25a20, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000558b49fb29f8 in SudoAskpassServer::Thread() ()
#2  0x0000558b49fb30b9 in SudoAskpassServer::sThread(void*) ()
#3  0x00007f47debd26db in start_thread (arg=0x7f47d4f27700)
    at pthread_create.c:463
#4  0x00007f47ddca588f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f47dfe88280 (LWP 18807)):
#0  0x00007f47ddc98bf9 in __GI___poll (fds=0x558b4ac51ff0, nfds=3, timeout=500)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f47de9005c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f47de900962 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f47dd671a37 in gtk_main ()
---Type <return> to continue, or q <return> to quit---
    at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#4  0x00007f47df4d6b05 in wxGUIEventLoop::DoRun() ()
    at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#5  0x00007f47dee89a93 in wxEventLoopBase::Run() ()
    at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#6  0x00007f47dee510a6 in wxAppConsoleBase::MainLoop() ()
    at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#7  0x00007f47deedbae9 in wxEntry(int&, wchar_t**) ()
    at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#8  0x0000558b49fc9bc2 in WinPortMainWX(int, char**, int (*)(int, char**), int*) ()
#9  0x0000558b49fb39a9 in WinPortMain ()
#10 0x00007f47ddba5b97 in __libc_start_main (main=
    0x558b49e352a0 <main>, argc=1, argv=0x7ffeb86e47a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffeb86e4798)
    at ../csu/libc-start.c:310
#11 0x0000558b49e379ca in _start ()
(gdb) 
```

**Comment by asimonov-hitachi** [comment]
and to reproduce i had to kill a VPN connection that the sftp was connected via

**Comment by elfmz** [comment]
Try this branch: https://github.com/elfmz/far2l/tree/remove-isbroken
And if issue will be still reproducable - get new stacktrace plz..

**Comment by asimonov-hitachi** [comment]
just built it and started to use. cannot reproduce the error on one try, which is good. lets see how it goes...

**Comment by elfmz** [comment]
So what? May merge&set as fixed or still unknown?

**Comment by asimonov-hitachi** [comment]
i did not get to use sftp last few days. but see no issues, so good to merge as far as i can tell :)
