### ISSUE TITLE
Зависание при доступе к папкам требующему повышения привилегий

### ISSUE THREAD

**Issue by itspec-ru** [elfmz/far2l#992]
Под обычным пользователем (для этого пользователя в sudoers ничего не прописано) пытаюсь зайти, например, в /root

В вехней части окна вижу запрос:

```
Операция требует повышения привилегий
Введите пароль для sudo
Confirm by <Enter> Cancel by <Esc>
```

Запрос появляется три раза, каждый раз жмём либо Enter, либо Esc (не имеет значения, привилегий то всё равно нет)

В итоге оказываюсь в /root
Содержимое папки не отображается (пусто).
И на этом всё, висим. Выйти из папки не получается. Командная строка не работает.

ОС Gentoo Linux, Calculate Linux
для сборки использовал свой ebuild
https://bitbucket.org/gentoo-overlay/itspec/src/master/app-misc/far2l/far2l-9999.ebuild

**Comment by elfmz** [comment]
А на убунте 18.04 у меня все хорошо.
1 Речь о GUI или TTY версии?
2 если воспроизводится в гуи, можете запустить ее под gdb: `gdb far2l` ввести команду `run`, воспроизвести ситуацию и затем в gdb нажать Ctrl+C и ввести команды `thread apply all bt` и показать весь ее вывод?

**Comment by itspec-ru** [comment]
Вывод после "thread apply all bt":

```
Thread 8 (Thread 0x7ffff19eb640 (LWP 24043) "far2l"):
#0  0x00007ffff720d5a3 in select () at /lib64/libc.so.6
#1  0x000055555570fdbf in  ()
#2  0x000055555570fee9 in  ()
#3  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7ffff29ed640 (LWP 24041) "far2l"):
#0  0x00007ffff71ddf51 in clock_nanosleep () at /lib64/libc.so.6
#1  0x00007ffff71e32c3 in nanosleep () at /lib64/libc.so.6
#2  0x00007ffff720de05 in usleep () at /lib64/libc.so.6
#3  0x000055555566163e in  ()
#4  0x000055555567e1f6 in  ()
#5  0x000055555567e458 in  ()
#6  0x000055555567a198 in  ()
#7  0x000055555567a95c in  ()
#8  0x000055555567aec5 in  ()
#9  0x000055555574291e in  ()
#10 0x00007ffff780865a in wxThread::CallEntry() () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#11 0x00007ffff7808a62 in  () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#12 0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#13 0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7ffff36ef640 (LWP 24040) "dconf worker"):
#0  0x00007ffff720afef in poll () at /lib64/libc.so.6
#1  0x00007ffff656b02e in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff656b14f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff3775d8d in  () at /usr/lib64/gio/modules/libdconfsettings.so
#4  0x00007ffff6593a6d in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7ffff3f93640 (LWP 24039) "gdbus"):
#0  0x00007ffff720afef in poll () at /lib64/libc.so.6
#1  0x00007ffff656b02e in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff656b393 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff5fbfd06 in  () at /usr/lib64/libgio-2.0.so.0
#4  0x00007ffff6593a6d in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7ffff47bf640 (LWP 24038) "gmain"):
#0  0x00007ffff720afef in poll () at /lib64/libc.so.6
#1  0x00007ffff656b02e in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff656b14f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff656b1a1 in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff6593a6d in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7ffff515b640 (LWP 24037) "far2l"):
#0  0x00007ffff720d5a3 in select () at /lib64/libc.so.6
#1  0x000055555575b1c1 in  ()
#2  0x0000555555724c18 in  ()
#3  0x0000555555724c89 in  ()
#4  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#5  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff55baa40 (LWP 24033) "far2l"):
#0  0x00007ffff66f9c10 in cairo_device_acquire () at /usr/lib64/libcairo.so.2
#1  0x00007ffff676a311 in  () at /usr/lib64/libcairo.so.2
#2  0x00007ffff676bb14 in  () at /usr/lib64/libcairo.so.2
#3  0x00007ffff674f926 in  () at /usr/lib64/libcairo.so.2
#4  0x00007ffff67501c4 in  () at /usr/lib64/libcairo.so.2
#5  0x00007ffff66f678e in  () at /usr/lib64/libcairo.so.2
#6  0x00007ffff6773201 in  () at /usr/lib64/libcairo.so.2
#7  0x00007ffff6747c6e in  () at /usr/lib64/libcairo.so.2
#8  0x00007ffff66ff0f5 in  () at /usr/lib64/libcairo.so.2
#9  0x00007ffff66f813a in  () at /usr/lib64/libcairo.so.2
#10 0x00007ffff675549a in cairo_fill () at /usr/lib64/libcairo.so.2
#11 0x00007ffff7c9d419 in wxCairoContext::FillPath(wxGraphicsPath const&, wxPolygonFillMode) () at /usr/lib64/libwx_gtk3u_core-3.0-gtk3.so.0
#12 0x00007ffff7cb18f6 in wxGraphicsContext::DrawPath(wxGraphicsPath const&, wxPolygonFillMode) () at /usr/lib64/libwx_gtk3u_core-3.0-gtk3.so.0
#13 0x00007ffff7cb3db5 in wxGraphicsContext::DrawRectangle(double, double, double, double) () at /usr/lib64/libwx_gtk3u_core-3.0-gtk3.so.0
#14 0x0000555555739d64 in  ()
#15 0x000055555573a12d in  ()
#16 0x000055555573ab22 in  ()
#17 0x00007ffff7838471 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#18 0x00007ffff7838563 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#19 0x00007ffff78388ac in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#20 0x00007ffff7838933 in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#21 0x00007ffff78389d1 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#22 0x00007ffff7838767 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#23 0x00007ffff7badcde in wxWindow::GTKSendPaintEvents(_cairo*) () at /usr/lib64/libwx_gtk3u_core-3.0-gtk3.so.0
#24 0x00007ffff7bae13b in  () at /usr/lib64/libwx_gtk3u_core-3.0-gtk3.so.0
#25 0x00007ffff6d4ef2b in  () at /usr/lib64/libgtk-3.so.0
#26 0x00007ffff6cf70ef in  () at /usr/lib64/libgtk-3.so.0
#27 0x00007ffff665af92 in g_closure_invoke () at /usr/lib64/libgobject-2.0.so.0
#28 0x00007ffff666deb4 in  () at /usr/lib64/libgobject-2.0.so.0
#29 0x00007ffff66787f8 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#30 0x00007ffff667965f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#31 0x00007ffff6d03e62 in  () at /usr/lib64/libgtk-3.so.0
#32 0x00007ffff6d0d300 in  () at /usr/lib64/libgtk-3.so.0
#33 0x00007ffff6bae028 in gtk_main_do_event () at /usr/lib64/libgtk-3.so.0
#34 0x00007ffff689f655 in  () at /usr/lib64/libgdk-3.so.0
#35 0x00007ffff68b0871 in  () at /usr/lib64/libgdk-3.so.0
#36 0x00007ffff68b2441 in  () at /usr/lib64/libgdk-3.so.0
#37 0x00007ffff68b2638 in  () at /usr/lib64/libgdk-3.so.0
#38 0x00007ffff665b1c6 in  () at /usr/lib64/libgobject-2.0.so.0
#39 0x00007ffff6679054 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#40 0x00007ffff667965f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#41 0x00007ffff68a93de in  () at /usr/lib64/libgdk-3.so.0
#42 0x00007ffff6893ca9 in  () at /usr/lib64/libgdk-3.so.0
#43 0x00007ffff656b884 in  () at /usr/lib64/libglib-2.0.so.0
#44 0x00007ffff656ad0e in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#45 0x00007ffff656b0c0 in  () at /usr/lib64/libglib-2.0.so.0
#46 0x00007ffff656b393 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#47 0x00007ffff6bad095 in gtk_main () at /usr/lib64/libgtk-3.so.0
#48 0x00007ffff7b84f15 in wxGUIEventLoop::DoRun() () at /usr/lib64/libwx_gtk3u_core-3.0-gtk3.so.0
#49 0x00007ffff76f859d in wxEventLoopBase::Run() () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#50 0x00007ffff76bfc76 in wxAppConsoleBase::MainLoop() () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#51 0x00007ffff77499f8 in wxEntry(int&, wchar_t**) () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#52 0x0000555555744380 in  ()
#53 0x0000555555725e72 in  ()
#54 0x00005555555a4587 in  ()
#55 0x00007ffff713fe6b in __libc_start_main () at /lib64/libc.so.6
#56 0x00005555555a6caa in _start ()

```

**Comment by itspec-ru** [comment]
Зависает и в консольной и в GUI. Вывод в предыдущем посте для GUI.
Вывод gdb до зависания:

```
GNU gdb (Gentoo 10.1 vanilla) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from far2l...
(No debugging symbols found in far2l)
(gdb) run
Starting program: /usr/bin/far2l 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
argv[0]='/usr/bin/far2l' g_strFarModuleName='/usr/bin/far2l' translation_prefix='/usr/'

[New Thread 0x7ffff515b640 (LWP 24742)]
[New Thread 0x7ffff47bf640 (LWP 24743)]
[New Thread 0x7ffff3f93640 (LWP 24744)]
[New Thread 0x7ffff36ef640 (LWP 24745)]
[New Thread 0x7ffff29ed640 (LWP 24746)]
[New Thread 0x7ffff21ec640 (LWP 24747)]
[New Thread 0x7ffff19eb640 (LWP 24748)]
[Detaching after fork from child process 24749]

Мы полагаем, что ваш системный администратор изложил вам основы
безопасности. Как правило, всё сводится к трём следующим правилам:

    №1) Уважайте частную жизнь других.
    №2) Думайте, прежде что-то вводить.
    №3) С большой властью приходит большая ответственность.

[Thread 0x7ffff21ec640 (LWP 24747) exited]
[Detaching after fork from child process 24756]

Мы полагаем, что ваш системный администратор изложил вам основы
безопасности. Как правило, всё сводится к трём следующим правилам:

    №1) Уважайте частную жизнь других.
    №2) Думайте, прежде что-то вводить.
    №3) С большой властью приходит большая ответственность.

itspec@itspec ~ $ gdb far2l
GNU gdb (Gentoo 10.1 vanilla) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from far2l...
(No debugging symbols found in far2l)
(gdb) run
Starting program: /usr/bin/far2l 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
argv[0]='/usr/bin/far2l' g_strFarModuleName='/usr/bin/far2l' translation_prefix='/usr/'

[New Thread 0x7ffff515b640 (LWP 24742)]
[New Thread 0x7ffff47bf640 (LWP 24743)]
[New Thread 0x7ffff3f93640 (LWP 24744)]
[New Thread 0x7ffff36ef640 (LWP 24745)]
[New Thread 0x7ffff29ed640 (LWP 24746)]
[New Thread 0x7ffff21ec640 (LWP 24747)]
[New Thread 0x7ffff19eb640 (LWP 24748)]
[Detaching after fork from child process 24749]

Мы полагаем, что ваш системный администратор изложил вам основы
безопасности. Как правило, всё сводится к трём следующим правилам:

    №1) Уважайте частную жизнь других.
    №2) Думайте, прежде что-то вводить.
    №3) С большой властью приходит большая ответственность.

itspec@itspec ~ $ gdb far2l
GNU gdb (Gentoo 10.1 vanilla) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from far2l...
(No debugging symbols found in far2l)
(gdb) run
Starting program: /usr/bin/far2l 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
argv[0]='/usr/bin/far2l' g_strFarModuleName='/usr/bin/far2l' translation_prefix='/usr/'

[New Thread 0x7ffff515b640 (LWP 24742)]
[New Thread 0x7ffff47bf640 (LWP 24743)]
[New Thread 0x7ffff3f93640 (LWP 24744)]
[New Thread 0x7ffff36ef640 (LWP 24745)]
[New Thread 0x7ffff29ed640 (LWP 24746)]
[New Thread 0x7ffff21ec640 (LWP 24747)]
[New Thread 0x7ffff19eb640 (LWP 24748)]
[Detaching after fork from child process 24749]

Мы полагаем, что ваш системный администратор изложил вам основы
безопасности. Как правило, всё сводится к трём следующим правилам:

    №1) Уважайте частную жизнь других.
    №2) Думайте, прежде что-то вводить.
    №3) С большой властью приходит большая ответственность.

```

**Comment by elfmz** [comment]
Выложите еще бинарник своего far2l так как gdb почемуто не показал символы на адресах которые очевидно смотрят в него (те которые на 0x000055555..). Надеюсь бинарник не пострипан.

**Comment by itspec-ru** [comment]
Да бинарник был действительно "пострипан". Пересобрал. Выкладываю всю "простыню" от начала до конца

```
$ gdb far2l
GNU gdb (Gentoo 10.1 vanilla) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from far2l...
(No debugging symbols found in far2l)
(gdb) 

(gdb) run
Starting program: /usr/bin/far2l 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
argv[0]='/usr/bin/far2l' g_strFarModuleName='/usr/bin/far2l' translation_prefix='/usr/'

[New Thread 0x7ffff515b640 (LWP 10640)]
[New Thread 0x7ffff47bf640 (LWP 10641)]
[New Thread 0x7ffff3f93640 (LWP 10642)]
[New Thread 0x7ffff36ef640 (LWP 10643)]
[New Thread 0x7ffff29ed640 (LWP 10657)]
[New Thread 0x7ffff21ec640 (LWP 10658)]
[New Thread 0x7ffff19eb640 (LWP 10659)]

```

ЗДЕСЬ Я ПЫТАЮСЬ ВОЙТИ В /root/, ДВА РАЗА ЖМУ esc

```
[Detaching after fork from child process 10665]

Мы полагаем, что ваш системный администратор изложил вам основы
безопасности. Как правило, всё сводится к трём следующим правилам:

    №1) Уважайте частную жизнь других.
    №2) Думайте, прежде что-то вводить.
    №3) С большой властью приходит большая ответственность.

[Thread 0x7ffff21ec640 (LWP 10658) exited]
[Detaching after fork from child process 10672]

Мы полагаем, что ваш системный администратор изложил вам основы
безопасности. Как правило, всё сводится к трём следующим правилам:

    №1) Уважайте частную жизнь других.
    №2) Думайте, прежде что-то вводить.
    №3) С большой властью приходит большая ответственность.

```
А ТУТ УЖЕ ВИСИМ
ЖМУ Ctrl+C

```
^C
Thread 1 "far2l" received signal SIGINT, Interrupt.
0x00007ffff720afef in poll () from /lib64/libc.so.6
(gdb)

```
ВВОЖУ КОМАНДУ thread apply all bt

```
Thread 8 (Thread 0x7ffff19eb640 (LWP 10659) "far2l"):
#0  0x00007ffff720d5a3 in select () at /lib64/libc.so.6
#1  0x000055555570fdbf in WinPortFSNotify::WatcherProc() ()
#2  0x000055555570fee9 in WinPortFSNotify::sWatcherProc(void*) ()
#3  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7ffff29ed640 (LWP 10657) "far2l"):
#0  0x00007ffff71ddf51 in clock_nanosleep () at /lib64/libc.so.6
#1  0x00007ffff71e32c3 in nanosleep () at /lib64/libc.so.6
#2  0x00007ffff720de05 in usleep () at /lib64/libc.so.6
#3  0x000055555566163e in GetInputRecord(_INPUT_RECORD*, bool, bool, bool) ()
#4  0x000055555567e1f6 in Manager::ProcessMainLoop() ()
#5  0x000055555567e458 in Manager::EnterMainLoop() ()
#6  0x000055555567a198 in MainProcess(FARString, FARString, FARString, int, int) ()
#7  0x000055555567a95c in MainProcessWithInterThreadCallsDispatching(FARString&, FARString&, FARString&, int, int) ()
#8  0x000055555567aec5 in FarAppMain(int, char**) ()
#9  0x000055555574291e in WinPortAppThread::Entry() ()
#10 0x00007ffff780865a in wxThread::CallEntry() () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#11 0x00007ffff7808a62 in  () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#12 0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#13 0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7ffff36ef640 (LWP 10643) "dconf worker"):
#0  0x00007ffff720afef in poll () at /lib64/libc.so.6
#1  0x00007ffff656b02e in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff656b14f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff3775d8d in  () at /usr/lib64/gio/modules/libdconfsettings.so
#4  0x00007ffff6593a6d in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7ffff3f93640 (LWP 10642) "gdbus"):
#0  0x00007ffff720afef in poll () at /lib64/libc.so.6
#1  0x00007ffff656b02e in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff656b393 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff5fbfd06 in  () at /usr/lib64/libgio-2.0.so.0
#4  0x00007ffff6593a6d in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7ffff47bf640 (LWP 10641) "gmain"):
#0  0x00007ffff720afef in poll () at /lib64/libc.so.6
#1  0x00007ffff656b02e in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff656b14f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff656b1a1 in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff6593a6d in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7ffff515b640 (LWP 10640) "far2l"):
#0  0x00007ffff720d5a3 in select () at /lib64/libc.so.6
#1  0x000055555575b1c1 in LocalSocketServer::WaitForClient(int) ()
#2  0x0000555555724c18 in SudoAskpassServer::Thread() ()
#3  0x0000555555724c89 in SudoAskpassServer::sThread(void*) ()
#4  0x00007ffff761aede in start_thread () at /lib64/libpthread.so.0
#5  0x00007ffff72158ff in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff55baa40 (LWP 10636) "far2l"):
#0  0x00007ffff720afef in poll () at /lib64/libc.so.6
#1  0x00007ffff656b02e in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff656b393 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff6bad095 in gtk_main () at /usr/lib64/libgtk-3.so.0
#4  0x00007ffff7b84f15 in wxGUIEventLoop::DoRun() () at /usr/lib64/libwx_gtk3u_core-3.0-gtk3.so.0
#5  0x00007ffff76f859d in wxEventLoopBase::Run() () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#6  0x00007ffff76bfc76 in wxAppConsoleBase::MainLoop() () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#7  0x00007ffff77499f8 in wxEntry(int&, wchar_t**) () at /usr/lib64/libwx_baseu-3.0-gtk3.so.0
#8  0x0000555555744380 in WinPortMainWX(int, char**, int (*)(int, char**), int*) ()
#9  0x0000555555725e72 in WinPortMain ()
#10 0x00005555555a4587 in main ()
(gdb)
(gdb) quit
A debugging session is active.

        Inferior 1 [process 10636] will be killed.

Quit anyway? (y or n) y
```

**Comment by itspec-ru** [comment]
Ссылка на бинарник
https://bitbucket.org/gentoo-overlay/itspec/downloads/far2l

**Comment by elfmz** [comment]
Все равно ниче не понятно:( по стекам все выглядет нормально, то есть зависона прямого нету, но возможно инпут не доходит изза каких нить проблем с системой приоритета ввода которая там именно для sudo существует. Добавил туда немного дебаг логов и запушил в ветку debug-992. Пожалуйста заберите ее, соберите из нее far2l, и сделайте следующее;
- откройте терминал
- введите команду FAR2L_STD=far2l.log
- и запустите новоскомпиленный far2l из этого терминала
- воспроизведите проблему за минимальное колво операций
- потыкайте стрелки курсора, ну и enter несколько раз чтоб в логе было видно и понятно когда это происходило
- закройте фар2л мышкой
- покажите получившийся far2l.log

**Comment by itspec-ru** [comment]
[far2l.log](https://github.com/elfmz/far2l/files/6369611/far2l.log)

**Comment by elfmz** [comment]
Похоже нашел прикопанную собаку. Попробуйте сейчас, уже с master-а.

**Comment by itspec-ru** [comment]
Похоже проблема решена.
Наблюдаю следующее поведение:
При попытке входа в каталог дважды производится запрос пароля, каждый раз отказываюсь по ESC.
В каталог попадаю, но содержимое не отображается (пусто).
Программа не висит, позволяет выйти из каталога.

Не понятно зачем повторно запрашивать пароль если я один раз уже отказался (нажал ESC)?
И ещё один момент. На мой взгляд логичнее было бы вообще не выполнять вход в каталог при отсутствии прав или после отказа по ESC, чем входить в пустой каталог (пользователь будет обманут мнимым пустым содержимым каталога).

**Comment by itspec-ru** [comment]
Не по теме.
Вспомнил про опечатку в интерфейсе NetRocks/Настройки подключения
"Пароль вход**я**"

И сиволы ":" в том же диалоговом окне не выровнены - гуляют по вертикали

Поправьте пожалуйста

**Comment by elfmz** [comment]
Некоторая неконсистность с поведением sudo объясняется тем что код этот работает слишком 'оторванно' от основной фаровской логики. Но в целом устранимо.

**Comment by itspec-ru** [comment]
Сейчас так:
запрашивается пароль, жму ESC
появляется красное окно
```
Ошибка
Error 5
root
```
с кнопками "Игнорировать", "Повторить"

при нажатии ESC (или Игнорировать) попадаю в пустую папку /root

**Comment by itspec-ru** [comment]
Напрашивается вопрос: а вообще так ли уж нужны заморочки с sudo?
Если требуется, не проще ли запускать far2l из под root'а?

**Comment by elfmz** [comment]
Нужны) А описанное поведение с заходом в недоступную диру - оно такое вне зависимости от sudo. Я тогда писал про двойной диалог, сейчас такого нет.

**Comment by elfmz** [comment]
все, исправил сию особенность поведения..

**Comment by itspec-ru** [comment]
Спасибо за наводку, не знал что sudo отключается. Лично мне без него удобнее.
При включенной sudo заметил ещё одну неприятную особенность:
если пытаться войти например в тот же /root от простого пользователя и на запрос пароля каждый раз жать просто Enter (не Esc), то войти в систему будет возможно только после истечения таймаута.
Учётная запись из под которой в far2l производилась попытка войти в /root блокируется, но в текущей сессии ничего не заметно. Проявляется только если выйти из графического окружения и попытаться зайти снова, или же попытаться войти в виртуальный терминал по Ctrl+Alt+F{1..6}, система ругается:
```
The account is locked due to 3 failed logins.
(10 minutes left to unlock)
```
На мой взгляд достаточно опасная реакция системы на попытку войти в "чужой" каталог.
